<script lang="ts">
    import type p5 from "p5";
    import { onMount, onDestroy } from "svelte";

    /** The raw JavaScript string of p5.js code generated by the AI. */
    export let p5Code: string;
    let canvasContainer: HTMLDivElement;
    let p5Instance: p5;

    onMount(async () => {
        // Dynamically import p5 on the client-side to prevent SSR errors.
        const p5Constructor = (await import("p5")).default;

        // This object will hold the functions we extract from the AI's code string.
        let sketchFunctions: {
            sketchSetup?: (p: p5) => void;
            sketchDraw?: (p: p5) => void;
        } = {};

        try {
            // Use the Function constructor to safely execute the AI's code string.
            // This defines sketchSetup and sketchDraw, which we then return.
            const executor = new Function(
                `${p5Code}; return { sketchSetup, sketchDraw };`,
            );
            const { sketchSetup, sketchDraw } = executor();

            if (
                typeof sketchSetup !== "function" ||
                typeof sketchDraw !== "function"
            ) {
                throw new Error(
                    "AI code did not correctly define sketchSetup and sketchDraw functions.",
                );
            }

            sketchFunctions.sketchSetup = sketchSetup;
            sketchFunctions.sketchDraw = sketchDraw;
        } catch (e) {
            console.error(
                "[P5Canvas] Error processing AI-generated p5 code:",
                e,
            );
            // If the AI code fails, assign a default error visual.
            sketchFunctions.sketchSetup = (p: p5) => {
                p.background(30, 0, 0);
                p.fill(255);
                p.textAlign(p.CENTER);
                p.text(
                    "Error: The AI-generated visual code failed to load.",
                    p.width / 2,
                    p.height / 2,
                );
            };
            sketchFunctions.sketchDraw = (p: p5) => {};
        }

        // The main sketch function passed to the p5 constructor.
        const sketch = (p: p5) => {
            p.setup = () => {
                p.createCanvas(p.windowWidth, p.windowHeight).parent(
                    canvasContainer,
                );
                // Call the setup function dynamically generated by the AI.
                if (sketchFunctions.sketchSetup) {
                    sketchFunctions.sketchSetup(p);
                }
            };

            p.draw = () => {
                // Call the draw function dynamically generated by the AI.
                if (sketchFunctions.sketchDraw) {
                    sketchFunctions.sketchDraw(p);
                }
            };

            p.windowResized = () => {
                p.resizeCanvas(p.windowWidth, p.windowHeight);
            };
        };

        // Create the new p5 instance with our dynamic sketch.
        p5Instance = new p5Constructor(sketch, canvasContainer);
    });

    onDestroy(() => {
        // This is critical to prevent memory leaks.
        if (p5Instance) {
            p5Instance.remove();
        }
    });
</script>

<!-- This div is the container where our p5.js canvas will be rendered. -->
<div bind:this={canvasContainer} class="w-full h-full fixed top-0 left-0 z-0" />

<style>
    /* We make the canvas container non-interactive so that UI elements (like the future
     gestural controls or buttons) can be placed on top of it. */
    div {
        pointer-events: none;
    }
</style>
